python train.py \
  --model vanilla \
  --dataset pokec_z \
  --encoder gcn \
  --lambda_dp 1.0 \
  --lambda_eo 1.0 \
  --advtrain --advtrain_attack edge_weight \
  --advtrain_mode robust --advtrain_k 3 \
  --advtrain_edge_policy same_smallest \
  --advtrain_edge_steps 5 \
  --advtrain_edge_step_size 0.1 \
  --advtrain_edge_grad sign \
  --advtrain_edge_w_max 1.0 \
  --advtrain_edge_budget -1
